import { Copy, Users, Gift, Share2, CheckCircle2, TrendingUp, Link as LinkIcon } from "lucide-react";
import { useState, useEffect } from "react";
import { useTelegram } from "../contexts/TelegramContext";
import { supabase } from "../lib/supabase";
import { motion, AnimatePresence } from "motion/react";

export function Referrals() {
  const { user } = useTelegram();
  const [copied, setCopied] = useState(false);
  const [referrals, setReferrals] = useState<any[]>([]);
  const [totalEarned, setTotalEarned] = useState(0);
  const [loading, setLoading] = useState(true);

  const refCode = user?.id ? `ref_${user.id}` : "ref_12345";
  const refLink = `https://t.me/PayvoraBot?start=${refCode}`;

  useEffect(() => {
    async function fetchReferrals() {
      if (!user?.uuid) return;
      try {
        const { data, error } = await supabase
          .from('referrals')
          .select('*, referred:referred_user_id(first_name, username)')
          .eq('referrer_id', user.uuid)
          .order('created_at', { ascending: false });

        if (data) {
          setReferrals(data);
          const earned = data.reduce((acc, curr) => acc + Number(curr.earned || 0), 0);
          setTotalEarned(earned);
        }
      } catch (err) {
        console.error("Error fetching referrals:", err);
      } finally {
        setLoading(false);
      }
    }
    fetchReferrals();
  }, [user?.uuid]);

  const copyToClipboard = () => {
    navigator.clipboard.writeText(refLink).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    });
  };

  const shareToTelegram = () => {
    const text = "Join me on Payvora and earn money completing simple offers!";
    const url = `https://t.me/share/url?url=${encodeURIComponent(refLink)}&text=${encodeURIComponent(text)}`;
    if ((window as any).Telegram?.WebApp?.openTelegramLink) {
      (window as any).Telegram.WebApp.openTelegramLink(url);
    } else {
      window.open(url, "_blank");
    }
  };

  return (
    <motion.div 
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      className="space-y-10 pb-10"
    >
      <header className="text-center lg:text-left">
        <span className="inline-block px-3 py-1 rounded-full bg-brand/10 text-brand text-[10px] font-bold uppercase tracking-[0.2em] mb-4">Affiliate Program</span>
        <h1 className="text-4xl lg:text-5xl font-display font-bold text-white tracking-tight mb-4 gradient-text">Network Growth</h1>
        <p className="text-slate-400 max-w-xl text-balance">
          Architect your own revenue stream by onboarding new partners to the Payvora ecosystem.
        </p>
      </header>

      {/* Hero Card */}
      <div className="relative group">
        <div className="absolute -inset-1 bg-gradient-to-r from-brand to-emerald-500 rounded-[2.5rem] blur opacity-15 group-hover:opacity-25 transition duration-1000"></div>
        <div className="relative premium-card border-white/10 !p-10 overflow-hidden">
          <div className="absolute top-0 right-0 p-8 opacity-5 mix-blend-overlay pointer-events-none group-hover:scale-110 transition-transform duration-1000">
            <Gift className="w-64 h-64 -rotate-12 text-white" />
          </div>

          <div className="relative z-10 flex flex-col items-center text-center max-w-2xl mx-auto">
            <div className="w-20 h-20 bg-brand/10 rounded-3xl flex items-center justify-center mb-8 border border-brand/20 shadow-2xl">
              <TrendingUp className="w-10 h-10 text-brand" />
            </div>
            <h2 className="text-3xl lg:text-4xl font-display font-bold text-white mb-4">Earn 10% Residual Income</h2>
            <p className="text-slate-400 text-lg mb-10 leading-relaxed">
              Unlock a lifetime 10% override on all platform distributions generated by your direct referrals.
            </p>
            
            <div className="w-full space-y-6">
              <div className="flex flex-col sm:flex-row gap-3">
                <div className="flex-1 bg-slate-950 border border-white/5 rounded-2xl p-4 flex items-center group/link">
                  <LinkIcon className="w-4 h-4 text-slate-600 mr-3 shrink-0" />
                  <p className="text-sm font-mono text-slate-400 truncate text-left">
                    {refLink}
                  </p>
                </div>
                <button 
                  onClick={copyToClipboard}
                  className="btn-primary !py-4 min-w-[140px]"
                >
                  {copied ? <CheckCircle2 className="w-4 h-4 mr-2" /> : <Copy className="w-4 h-4 mr-2" />}
                  {copied ? "Copied" : "Copy Link"}
                </button>
              </div>
              <button 
                onClick={shareToTelegram}
                className="w-full flex items-center justify-center space-x-3 bg-white/5 hover:bg-white/10 text-white rounded-2xl py-5 transition-all border border-white/5 font-bold"
              >
                <Share2 className="w-5 h-5 text-brand" />
                <span>Propagate to Telegram Contacts</span>
              </button>
            </div>
          </div>
        </div>
      </div>

      {/* Stats Grid */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        <div className="premium-card flex items-center space-x-6 border-white/5">
          <div className="w-16 h-16 rounded-2xl bg-brand/10 flex items-center justify-center text-brand border border-brand/20">
            <Users className="w-8 h-8" />
          </div>
          <div>
            <p className="text-xs font-bold text-slate-500 uppercase tracking-widest mb-1">Direct Partners</p>
            <p className="text-4xl font-display font-bold text-white">{referrals.length}</p>
          </div>
        </div>
        
        <div className="premium-card flex items-center space-x-6 border-white/5">
          <div className="w-16 h-16 rounded-2xl bg-emerald-500/10 flex items-center justify-center text-emerald-500 border border-emerald-500/20">
            <Gift className="w-8 h-8" />
          </div>
          <div>
            <p className="text-xs font-bold text-slate-500 uppercase tracking-widest mb-1">Cumulative Rewards</p>
            <p className="text-4xl font-display font-bold text-emerald-400">${totalEarned.toFixed(2)}</p>
          </div>
        </div>
      </div>

      {/* Referrals Ledger */}
      <div className="space-y-6">
        <h3 className="text-2xl font-display font-bold text-white px-2">Network Ledger</h3>
        
        <div className="premium-card !p-0 border-white/5 overflow-hidden">
          {loading ? (
             <div className="p-12 text-center text-slate-500 font-bold uppercase tracking-[0.2em] animate-pulse">Scanning Network...</div>
          ) : referrals.length === 0 ? (
             <div className="p-20 text-center flex flex-col items-center justify-center">
               <div className="w-20 h-20 rounded-[2rem] bg-slate-900 border border-white/5 flex items-center justify-center mb-6">
                 <Users className="w-10 h-10 text-slate-700" />
               </div>
               <p className="text-white font-bold text-xl mb-2">No Active Nodes</p>
               <p className="text-slate-500 text-sm max-w-sm mx-auto text-balance">
                 Your affiliate network is currently inactive. Use the portal above to onboard your first partner.
               </p>
             </div>
          ) : (
            <div className="divide-y divide-white/5">
              {referrals.map((ref, i) => {
                const name = ref.referred?.first_name || ref.referred?.username || 'Partner';
                return (
                  <motion.div 
                    key={ref.id} 
                    initial={{ opacity: 0, x: -20 }}
                    animate={{ opacity: 1, x: 0 }}
                    transition={{ delay: i * 0.05 }}
                    className="p-8 flex items-center justify-between hover:bg-white/[0.03] transition-all group"
                  >
                    <div className="flex items-center space-x-6">
                      <div className="w-14 h-14 rounded-2xl bg-brand/5 border border-brand/10 text-brand flex items-center justify-center font-display font-bold text-xl group-hover:bg-brand/20 transition-all duration-500">
                        {name[0].toUpperCase()}
                      </div>
                      <div>
                        <h4 className="font-bold text-white text-base group-hover:text-brand transition-colors">{name}</h4>
                        <div className="flex items-center space-x-2 mt-1">
                          <CheckCircle2 className="w-3 h-3 text-emerald-500" />
                          <p className="text-[10px] text-slate-500 font-bold uppercase tracking-widest">Active Since {new Date(ref.created_at).toLocaleDateString()}</p>
                        </div>
                      </div>
                    </div>
                    <div className="text-right">
                      <p className="text-[10px] text-slate-500 font-bold uppercase tracking-widest mb-1">Your Yield</p>
                      <p className="font-display font-bold text-emerald-400 text-xl">${Number(ref.earned).toFixed(2)}</p>
                    </div>
                  </motion.div>
                );
              })}
            </div>
          )}
        </div>
      </div>
    </motion.div>
  );
}
